### ISSUE TITLE
Usage of "type" in labels.json

### ISSUE THREAD

**Issue by Berkmann18** [bond-agency/github-label-maker#3]
This project seems great and I'm looking into using it.
I've noticed that the `label.json` isn't the standard `labels.json` that Github projects would have; notably when it comes to the [API](https://developer.github.com/v3/issues/labels/) which don't have any "type" key in the JSON file.
Is that meant to be that way or was that purely to split labels on the package side?

**Comment by sarukuku** [comment]
I think @roopemerikukka is the one to answer your question. :)

**Comment by roopemerikukka** [comment]
Hi @Berkmann18 and sorry that the answer took so long.

Yeah it's true that the `labels.json` doesn't follow the API pattern but it's just used to populate the labels in there to the repository. The idea behind the labels system came from here: https://robinpowered.com/blog/best-practice-system-for-organizing-and-tagging-github-issues/

The type is used together with the name in [here](https://github.com/bond-agency/github-label-maker/blob/master/functions.rb#L52) to make the labels look like this:

![screenshot 2018-12-13 at 16 27 52](https://user-images.githubusercontent.com/1453463/49944835-16a22300-fef4-11e8-8094-2ea3a1d3aba0.png)

**Comment by Berkmann18** [comment]
Ah okay, it makes sense.
